project:
  type: website

website:
  title: " Introducción a la álgebra lineal Computacional"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - section1.ipynb
      - section2.ipynb
      - section3.qmd
      - ejercicio.ipynb
      - section4.qmd
      - section5.qmd
      - section6.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



