---
title: "Minímos cuadrados 1"
format: html
---
Sea $A$ una matriz de $m\times n$ y $b$ un vector de $\mathbb{R}^m$. El problema de mínimos cuadrados es encontrar $\overline{x}\in \mathbb{R}^n$ tal que
$$mim_{\overline{x}}\|A\overline{x}-y\|.$$
Para encontrar esto podemos usar el teorema de la proyección ortogonal. Sea $y\in \mathbb{R}^m$ y $N(A^T)$ el espacio nulo de $A^T$ y $C(A)$ el espacio columna de $A$. Entonces

Sea $y\in \mathbb{R}^m$ luego $y=y_1+y_2$ con $y_1\in N(A^T)$ y $y_2\in C(A)$ entonces

$$A^Ty=A^T(y_1+y_2)=A^Ty_1+A^Ty_2=A^Ty_2,$$

como $y_2\in C(A)$ entonces existe un $\overline{x}$ tal que
$$A\overline{x}=y_2,$$ 
 sustituyendo en la primera ecuación tenemos que
 $$A^TA\overline{x}=A^Ty.$$

 Como $A^TA$ es simétrica y e invertible tenemos que
  $$\overline{x}=(A^TA)^{-1}A^T y.$$


Ejemplo


Supongamos que tenemos un sistema de tres ecuaciones y dos incognitas como el siguiente 
$$\begin{cases}x_1+x_2=2\\
x_1-x_2=1\\
x_1+x_2=3\end{cases},$$
este sistema lo podemos escribir en forma matricial $Ax=b$ de la siguiente forma 

$$\begin{bmatrix}1&1\\1&-1\\1&1\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}=\begin{bmatrix}2\\1\\3\end{bmatrix}.$$

Note que esto lo podemos escribir como 

$$\begin{bmatrix}1\\1\\1\end{bmatrix}x_1+\begin{bmatrix}1\\-1\\1\end{bmatrix}x_2=\begin{bmatrix}2\\1\\3\end{bmatrix}.$$

De esta forma lo que queremos es encontrar la proyección del vertor $\begin{bmatrix}2\\1\\3\end{bmatrix}$
en el generado por el conjunto de vectores $$\Big\{\begin{bmatrix}1\\1\\1\end{bmatrix},\begin{bmatrix}1\\-1\\1\end{bmatrix}\Big\},$$

Gráficamente lo podemos interpretar como muestra la siguiente gráfica